spring:
  datasource:
    url: jdbc:postgresql://localhost:13551/tasklist?currentSchema=tasklist
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
#    secret: ${JWT_SECRET}
    secret: ZnRoZm5kZmdubWosZ2hqbWdobktGSUtLSEdDS0hHQ0NZVEtHSHhkZnZkZnY=
    access: 3600000
    refresh: 2592000000
#springdoc:
#  override-with-generic-response: false
